import '@fortawesome/fontawesome-free/css/all.css'
import './globals.css'
import profilePic from '../public/milo1.JPG'
import { Navigation } from '@/components/Navigation'
import Card from '@/components/Card'
//import { Inter } from 'next/font/google'

//const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My portfolio',
  description: 'Generated by create next app',
}
// https://bootswatch.com/5/morph/bootstrap.min.css
// https://bootswatch.com/5/cyborg/bootstrap.min.css
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <link rel='stylesheet' href='https://bootswatch.com/5/lux/bootstrap.min.css' />
        
      </head>
      <body>

        <div className="container">
          <div className="row" style={{placeContent: 'center'}}>
              <div className='col-lg-10' style={{ maxWidth: '800px', placeItems: 'center' }}>
                {/* , border: '1px solid red' */}
                <section style={{ width: '100%' }}>
                  <Card imagePath={profilePic}/>
                  {/* CONTACT INFO - SOCIAL MEDIA */}
                  <Navigation />
                </section>
                <section className='mt-5' style={{ width: '100%' }}>
                  {children}
                </section>
              </div>
          </div>
        </div>

      </body>
    </html>
  )
}
